### ISSUE TITLE
As a user, I can access login date form all other user. Is this a feature ? 

### ISSUE THREAD

**Issue by maxired** [hckrs/hckrs.io#110]
In my browsers console, when loggued, if I do 
```
Meteor.users.find({}).fetch();
```
Then I retrieved information about all users. Some of it is probably not public information.

For example, we can find email address of people not 'available' to email
with 
```
Meteor.users.find({}).fetch().filter(function(el){ return el.profile.available}).filter(function(el){ return el.profile.available.indexOf("email")==-1 &&  el.profile.email})
```
Another field I am worried about is the 'accessAt' field

**Comment by JarnoLeConte** [comment]
It's still correct probably.

Because your email address will become public if you check one of the following options in your profile at **available to** `['drink','lunch','email','cowork','couchsurf']`. Furthermore, email addresses of ambassadors and admins are public.

To check if this predicate hold for the users you queried, run the following code snippet in the console. Please let me know if this is correct.
```
query = Meteor.users.find({}).fetch().filter(function(el){ return el.profile.available}).filter(function(el){ return el.profile.available.indexOf("email")==-1 &&  el.profile.email});
_.all(query, function(u){  return u.isAdmin || u.isAmbassador || _.intersection(u.profile.available, ['drink','lunch','email','cowork','couchsurf']).length > 0; });
```


Of course we can discuss the issue further, because maybe it's not preferred to query email addresses that easily. Although public is public. In the same way you can retrieve user's email addresses from populair sites (for example from Github). But we could discuss the usage of encryption of course.

You mentioned also the **access at** field. This is nearly the same as *date of registration*. I think that would not attack user's privacy.

**Comment by maxired** [comment]
Hi,

thanks for your feedback.

It was not clear to me, that if I say i am available to 'anything', this
will disclose my mail.
Most others websites with this kind of features have private message, or a
way to send mail without disclosure.

**Comment by JarnoLeConte** [comment]
Anyway, thank you for creating the issue, because it is always good to revisit the current approach. 

There are ideas to use such built-in system to send emails through dynamic addresses with @hckrs.io domain. In that case we can hide user's email completely. 
We are still searching for people that have experience with setting up such system.

Right now it is implemented this way.  When clicking one of the **available to** checkboxes we point out that your email will become public.

**Comment by thomasguillory** [comment]
> We are still searching for people that have experience with setting up such system.
Hi Jarno,
I've already built such a system (in Ruby not in Meteor but still).
I have no time to contribute but I can point you on the right way.

**Comment by JarnoLeConte** [comment]
That sounds great. It could be very useful to listen to your ideas about how to setup such thing.
Is it something we could discuss over Skype, or would you just put some ideas on Github or email?

**Comment by thomasguillory** [comment]
Finding the good time to Skype will be a hassle, I drop you the key ideas by email !

**Comment by JarnoLeConte** [comment]
There is now feature request #114 to implement a messaging system, so that we don't need to expose user email addresses.

This issue can be closed.
