### ISSUE TITLE
Custom city picture

### ISSUE THREAD

**Issue by jimtolman** [hckrs/hckrs.io#121]
In an earlier version of hckrs.io there were custom city pictures, differing per hckrs tribe. Maybe this can be brought to newer version of hckrs.io? I heard our new hckr in Hong Kong makes nice pictures: https://www.flickr.com/photos/129202717@N03/

**Comment by ramshorst** [comment]
Do you mean for the frontpage, or as a blurred background on the entire website?
For the blurred background it's king of hard to make sure contrast works ok on al pages, but for the 'clear' frontage that seams possible. Did you have a specific image in min @jimtolman? What do you think about that @JarnoLeConte ? We should move our images to the assets FTP server with the next release!

**Comment by jimtolman** [comment]
I meant for the frontpage or maybe even for the blurred background. I don't know what is possible. A specific picture for Hong Kong could be http://i.imgur.com/8Ry1W87.jpg or http://i.imgur.com/V5XB1Il.jpg (both made by Michelle's, yet with decreased exposure and highlights. For Rotterdam maybe http://bit.ly/1DOzMFX or http://bit.ly/1IB6lqa.

**Comment by JarnoLeConte** [comment]
I still like the idea to use local pictures. It is important the stay focussing on that local aspect of hckrs.io. 

On the other side the current picture is very good, so we must only use customized pictures if it is really an improvement. 

If there are good pictures I like to use them both on frontpage and as blur-background. 

Furthermore I prefer to use pictures with same brightness. What I mean is that it isn't a good idea to use dark (night) pictures in one city and colorful bright (daylight) pictures in some other city, because it will give a completely different feeling. Or doesn't this make any sense?

The idea to have different day and night backgrounds is also nice!

It is a good idea to test what kind of pictures (color / intensity) work well. I don't like to use shadow to solve the problem, although gaussian-blur is open for experiments. That kind of blur works very well for the current background at least. 

An alternative is to use different CSS schemes based on the background to make sure there is enough contrast with text. But I think this becomes too much and we can better keep a single style for hckrs.io.

**Comment by ramshorst** [comment]
I agree with everything Jarno said :) The technical issue right now is that we need to host all our images on de assets FTP so that we are more flexible. The best would be if we can change images without having to put a net cities.js file in production each time. We could also set up a weekly release but i don’t know it that is manageable ?

**Comment by JarnoLeConte** [comment]
The cities.js have to move to the database. This can be done in the 'locationpicker+cities' release. Then background images can be easily changed. Or indeed keep the URL pointing to static server and change the image there ;-)

The idea of releasing faster is possible as long we keep the development branch clean and production ready. Then entering a simple command to push the branch to the server is sufficient. 



> Op 7 apr. 2015 om 18:40 heeft ramshorst <notifications@github.com> het volgende geschreven:
> 
> I agree with everything Jarno said :) The technical issue right now is that we need to host all our images on de assets FTP so that we are more flexible. The best would be if we can change images without having to put a net cities.js file in production each time. We could also set up a weekly release but i don’t know it that is manageable ?
> 
>

**Comment by ramshorst** [comment]
Sounds good!

As for keeping the development branch ready; I think that kind of what we do right now right ?
Could we get it to the point where we automate it so that it goes in production every sunday for example ? Or does that not make sense ?
