### ISSUE TITLE
Growth statistics

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#122]
First mock-up. What do you think ?

![screen shot 2015-04-04 at 02 09 25](https://cloud.githubusercontent.com/assets/5200239/6990592/c35b0f88-da6f-11e4-8af1-77c9772ca697.png)

**Comment by JarnoLeConte** [comment]
Graphs looks nice, always!!! :)

Understand I correctly:
- list campaigns with open, click, signup rates. 
- show total open, click and sign up rates for all campaigns together. 
- do you mean with conversion the fraction sign ups from the emails opened / or clicked?
- targets could be set manually? Is this based on a specific time interval?

So although I like the mock-up, the stats are not directly clear to me, but on the other side I see already potential, because it give more feedback than is available right now. 



Verstuurd vanaf mijn iPhone
