### ISSUE TITLE
Telescope integration

### ISSUE THREAD

**Issue by MartinDelille** [hckrs/hckrs.io#123]
Wouldn't it be cool to have this app integrated? https://github.com/TelescopeJS/Telescope

**Comment by ramshorst** [comment]
This is something we worked on before! @JarnoLeConte, could you give @MartinDelille some advice on to achieve this ? I think the goal for now is to put telescope as a menu item in the menu. The hardest part is probably to link the user system with our existing system.

**Comment by JarnoLeConte** [comment]
Indeed, we started merging telescope in the hckrs.io project, but it gets stuck, because of the overlapping functionality and collections. I not know anymore what exactly was the bottleneck, but it turns out that is was    better to copy the good parts (like UI and posting functionality) and integrate it in hckrs.io manually, although this not scalable for further Telescope updates. 

A lot is changed in the meantime. hckrs.io started using general libraries, for example Iron-Router, and Telescope is also further developed, which maybe means they split out functionality. So probably there are new possibilities now. 

If Telescope is built of packages now a days, we can possibly integrate the packages individually. The advantage would be easy update if Telescope update her packages. And we have full control of the integration. 

Less attractive is the idea to run Telescope isolated, because I don't see how we could combine it in the future with great features specified in our roadmap. Or do you have other thoughts on this, or could isolation a good temporary solution?

Could you specify a list of the great features of Telescope? So that it is easier to focus on the necessary parts?
I think the main idea is to copy the message board (topics), run it on a separate page, and uses our users collection. But is that easily possible?

**Comment by Dandandan** [comment]
Telescope is not a package yet.

Relevant links: 

https://trello.com/c/lBJnNsC4/218-make-telescope-a-package
http://meta.telesc.pe/posts/HuHzZ5fBzWWiZnkwf/comment/fBiJRd59hjhAtBp6u

**Comment by MartinDelille** [comment]
@JarnoLeConte what do you think of adding Telescope as a git submodule of hckrs.io? There is still this login issue that we have to find out how to do.

**Comment by JarnoLeConte** [comment]
This should be possible. Then the plan could be as follows:

- We must make sure our users collection contains all required fields used by Telescope. 
- And we must change the publish/subscribe and allow/deny rules for the users collection, in order to let Telescope work properly. 
- Get rid of Telescopes signup/login. 
- Also a big problem to solve (at least in my first try to integrate) is preventing name clashes in global functions and fix the import order of all files. I think this could be handled the best when we put the git submodule in a package. 

If these things can be solved, you also solve the problem of packaging Telescope, which probably is good work! :-)

**Comment by MartinDelille** [comment]
Hi @ramshorst ! Are you back on the project?

**Comment by ramshorst** [comment]
Hi Martin :) 
We are thinking about it, why?
++ Toon

**Comment by MartinDelille** [comment]
Just to know! I'm might be interested for recruitement in the future.

**Comment by ramshorst** [comment]
What do you mean @MartinDelille :) ?

**Comment by MartinDelille** [comment]
Currently our development department is located in Paris. I'd like to move it to Lyon.
