### ISSUE TITLE
Display bug when company field is empty

### ISSUE THREAD

**Issue by Xalava** [hckrs/hckrs.io#73]
On hacker page, when the company field is empty, the map goes up in front of "company/school" label
![hckrscompay](https://cloud.githubusercontent.com/assets/7526343/5778051/89d536c6-9d98-11e4-839b-00cf924ca762.png)

**Comment by Jarnoleconte** [comment]
I think it isn't a bug, but probably not clear how it is working right now. 
The label in front of the map is actually called "company / school" because the intended behavior is to locate your company or school. 
In addition to this you can fill in a company name and URL which will be displayed along to it. 

Maybe we must use different names?

**Comment by Xalava** [comment]
I see three options then: 
- The location field is independent. As there are coworking and couchsurfing options below, the user, sorry, hckr, decides where he wants to be located. Anyway it's just an indication.
- Two marks: house and company
- If there is no company, the map could disappear too

**Comment by ramshorst** [comment]
The map sets the location for the place you are most often, so we figured that it the same for your company / your school, and the coworking place, and the couch surfing place.

**Comment by ramshorst** [comment]
This is resolve isn't it @Xalava ?
