### ISSUE TITLE
Kadira / page load time

### ISSUE THREAD

**Issue by ramshorst** [hckrs/hckrs.io#76]
Zou jij dat kunnen testen als je tijd hebt @JarnoLeConte ?

**Comment by ramshorst** [comment]
@Dandandan, @Rebolon told me that we should also use http://www.webpagetest.org/result/150225_MB_NXH/
Apparently you can get even more information if you make an account.
It will also be an interesting tool to see if we get better or worse over time.

**Comment by JarnoLeConte** [comment]
Kadira is now added in 9e7c3fed0a2f4ad88776293881ae8a779f386348

**Comment by Dandandan** [comment]
Do we have a (free) Kadira account?

**Comment by JarnoLeConte** [comment]
Kadira is now online, but attached to my personal meteor account. I could change the password, then you can login too. 
Locally you can always attach your own kadira account for testing. The only thing you have to do is providing your credentials in de settings/dev.json file.

**Comment by Dandandan** [comment]
I would like to see the Kadira numbers in production, so a login would be nice :).

**Comment by JarnoLeConte** [comment]
I will send you the credentials. 

By the way, I like to know how to read/interpret the performance measures. Maybe you can teach me how it works, someday ^_^

**Comment by JarnoLeConte** [comment]
It would be nice if we make a separate Kadira account for hckrs.io (todo).

**Comment by Dandandan** [comment]
Thanks!

Well, the most useful measure for us is I think the response time of the subscriptions. I think there is some low hanging fruit in the , we probably can remove some fields and move them to pages which need the said data. I guess the subscriptions `users`, `highlights` and `highlightsSort` are the most important to optimize, and maybe `mapHackersLocations`. What do you think?

These are the subscriptions with the highest response time:
![screenshot from 2015-03-08 10 37 57](https://cloud.githubusercontent.com/assets/163737/6545300/073eb510-c580-11e4-9ae9-bf5ae49e68de.png)

**Comment by Dandandan** [comment]
But I must say these numbers are probably inflated by admin accounts (as they subscribe to the whole user collection instead of city only).

**Comment by JarnoLeConte** [comment]
These results don't really surprise me, because these are the queries that involve some **unnecessary** complexity. I think we must start with optimizing the users pubsub, because that one is the most complex and, aside from the long response time, there is too much data in the client that slows down the client.

I suggest to rewrite the whole publish('users') code because now it is 1 big complex function, doing a lot of permission checks and filtering fields based on the current logged in user permission (admin, ambassador, user) that I made reactive through an additional server-side observer that checks for permission changes. 

Starting with removing the server side reactivity we can rewrite the code in 2 ways:

1. We keep one publish function but remove the reactivity be removing the observer. Instead we can pass the permission set we like to subscribe from the client, which determines which fields to include.
2. We can also split up the publications for each type of permission. So that we can subscribe in /Routes.js only the (possible multiple) subscriptions that we need. Each publication describes a set of fields to publish.

*Anyway, I think that we still need to do the publication manually, because determine if some field need to be included depends not only on the logged in user but also on the published user doc itself, because for example if the user wants make his email address private we have to exclude that field, but therefore the document must be queried first, so we have to do the filtering afterwards and publish the new doc manually.*

Additional we must make the subscriptions more flexible, so that we can reuse it in several pages. We must think of subscriptions that allows subscribing to sets of users (by group or manually specified in a list of user Ids) and we also need the flexibility of specify the fields we like to retrieve. Maybe we can specify groups of fields too.

So this are a lot requirements in my opinion, and we must first determine what the best structure of pubsub is. Do you have any suggestions? This is a raw set of (unstructured) possibilities:
```
subscribe('currentUser')
subscribe('allUsersFromMyCity', {fields: [field1, field2})   // individual fields
subscribe('allUsersFromMyCity', {fields: {profile: true, status: true}})   // field groups
subscribe('users', {users: [id1, id2], fields: [field1, field2]})   // retrieve this users
subscribe('users', {users: {city: ["Utrecht"]}, fields: [field1, field2]})   // retrieve group of users
subscribe('users', {users: [id1], permission: ["ambassador", "admin"]}) // include (reactive) permission
```
*This is only a quick sketch. It's worth to think at all possibilities first and choose the right structure*

I wonder what your ideas are.
